### ISSUE TITLE
ruby 2.7.1 deprecation warnings

### ISSUE THREAD

**Issue by josh-m-sharpe** [googleapis/google-api-ruby-client#890] opened 2020-07-07 16:22 UTC
It seems that creating a request object in this manner results in deprecation warnings stemming from ruby 2.7.1.  This rails issue seems related: https://github.com/rails/rails/issues/38202

I didn't see an issue anywhere that was tracking these deprecations.  Apologies if this is already tracked.

```ruby
request = Google::Apis::SheetsV4::BatchUpdateSpreadsheetRequest.new({
  requests: [{
    add_sheet: Google::Apis::SheetsV4::AddSheetRequest.new({
      properties: Google::Apis::SheetsV4::SheetProperties.new({
        title: "Some Title"
      })
    })
  }]
})

response = client.batch_update_spreadsheet(SPREADSHEET_ID, request)
```

```
(irb):67: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/me/.rvm/gems/ruby-2.7.1/gems/google-api-client-0.41.2/generated/google/apis/sheets_v4/classes.rb:8979: warning: The called method `initialize' is defined here
(irb):66: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/me/.rvm/gems/ruby-2.7.1/gems/google-api-client-0.41.2/generated/google/apis/sheets_v4/classes.rb:311: warning: The called method `initialize' is defined here
(irb):64: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/me/.rvm/gems/ruby-2.7.1/gems/google-api-client-0.41.2/generated/google/apis/sheets_v4/classes.rb:2014: warning: The called method `initialize' is defined here```

**Comment by dazuma** [comment] 2020-07-15 18:29
Need to update the generator templates.

**Comment by stanhu** [comment] 2020-12-29 15:25
Note that these deprecation warnings are now hard failures in Ruby v3.0.

**Comment by dazuma** [comment] 2020-12-31 19:17
I was looking at this now. The usage provided in the original report is incorrect. Arguments to object constructors are keyword arguments, not hashes.

Instead of:

```ruby
request = Google::Apis::SheetsV4::BatchUpdateSpreadsheetRequest.new({
  requests: [{
    add_sheet: Google::Apis::SheetsV4::AddSheetRequest.new({
      properties: Google::Apis::SheetsV4::SheetProperties.new({
        title: "Some Title"
      })
    })
  }]
})

response = client.batch_update_spreadsheet(SPREADSHEET_ID, request)
```

Please use:

```ruby
request = Google::Apis::SheetsV4::BatchUpdateSpreadsheetRequest.new(
  requests: [{
    add_sheet: Google::Apis::SheetsV4::AddSheetRequest.new(
      properties: Google::Apis::SheetsV4::SheetProperties.new(
        title: "Some Title"
      )
    )
  }]
)

response = client.batch_update_spreadsheet(SPREADSHEET_ID, request)
```

Closing this as working as intended. Please fix your calling code. If you got your current usage from some documentation or samples, it's possible those need to be corrected as well. (I checked the documentation in this repo, and didn't see any problems, but let me know if I missed something.)

**Closed by dazuma** 2020-12-31 19:17 UTC
Labels: priority: p2, type: bug
