### ISSUE TITLE
Google::Apis::ServerError: getaddrinfo: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.  (www.googleapis.com:443)

### ISSUE THREAD

**Issue by pratibha31** [googleapis/google-api-ruby-client#762] opened 2019-02-07 13:14 UTC
I am getting this error while uploading to Google Drive.
Sending upload start command to https://www.googleapis.com/upload/drive/v3/files?fields=%2A

google_session.upload_from_file('public/abc.txt','ABC', convert: false)

Rails version 4.0.4
gem google-drive 2.0
gem google-api-client 0.10.0

**Comment by blowmage** [comment] 2019-02-07 16:06
Are you running on Windows? If not, what platform are you on?

**Comment by blowmage** [comment] 2019-02-07 16:12
A `Google::Apis::ServerError` error is raised when the API returns a HTTP 5xx status. So my first impression here is that this looks like an error on the Google Drive API side, and not a problem with the Ruby client. The error description is common to DNS errors.

How long have you been getting this error? Are you able to reproduce this on a different computer to rule out a DNS issue on the current computer?

**Comment by blowmage** [comment] 2019-02-08 14:50
How are you configuring google-api-client to connect through the proxy?

**Comment by blowmage** [comment] 2019-02-08 14:50
Can you post some example code of what you are doing?

**Comment by blowmage** [comment] 2019-02-08 15:41
The should add, the google-api-client version you are using is 2 years old. I believe proxy support is more recent than that. I would definitely upgrade and see if the current version solves this issue.

**Comment by pratibha31** [comment] 2019-02-10 17:42
How can I configure proxy for google-api-client??

**Comment by pratibha31** [comment] 2019-02-11 07:31
When I am setting proxy in my project, getting below error 

Error - #<Google::Apis::ServerError: unsupported proxy ‪proxy.xyz.com:8080‬>

Google::Apis::ServerError: unsupported proxy ‪proxy.xyz.com:8080‬
        from D:/g_drive_local/BMajor/gems/google-api-ruby-client-0100/google-api-ruby-client-0.10.0/lib/google/apis/core/upload.rb:231:in `rescue in send_start_command'
        from D:/g_drive_local/BMajor/gems/google-api-ruby-client-0100/google-api-ruby-client-0.10.0/lib/google/apis/core/upload.rb:214:in `send_start_command'
        from D:/g_drive_local/BMajor/gems/google-api-ruby-client-0100/google-api-ruby-client-0.10.0/lib/google/apis/core/upload.rb:279:in `execute_once'
        from D:/g_drive_local/BMajor/gems/google-api-ruby-client-0100/google-api-ruby-client-0.10.0/lib/google/apis/core/http_command.rb:107:in `block (2 levels) in execute'
        from D:/Ruby/ruby gems/ruby/lib/ruby/gems/2.0.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
        from D:/Ruby/ruby gems/ruby/lib/ruby/gems/2.0.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
        from D:/Ruby/ruby gems/ruby/lib/ruby/gems/2.0.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
        from D:/g_drive_local/BMajor/gems/google-api-ruby-client-0100/google-api-ruby-client-0.10.0/lib/google/apis/core/http_command.rb:104:in `block in execute'
        from D:/Ruby/ruby gems/ruby/lib/ruby/gems/2.0.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
        from D:/Ruby/ruby gems/ruby/lib/ruby/gems/2.0.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
        from D:/Ruby/ruby gems/ruby/lib/ruby/gems/2.0.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
        from D:/g_drive_local/BMajor/gems/google-api-ruby-client-0100/google-api-ruby-client-0.10.0/lib/google/apis/core/http_command.rb:96:in `execute'
        from D:/g_drive_local/BMajor/gems/google-api-ruby-client-0100/google-api-ruby-client-0.10.0/lib/google/apis/core/base_service.rb:353:in `execute_or_queue_command'
        from D:/g_drive_local/BMajor/gems/google-api-ruby-client-0100/google-api-ruby-client-0.10.0/generated/google/apis/drive_v3/service.rb:579:in `create_file'
        from D:/g_drive_local/BMajor/gems/google-drive-ruby-200/google-drive-ruby-2.0.0/lib/google_drive/session.rb:409:in `upload_from_source'
        from D:/g_drive_local/BMajor/gems/google-drive-ruby-200/google-drive-ruby-2.0.0/lib/google_drive/session.rb:308:in `upload_from_file'
        from (irb):2
        from D:/Ruby/ruby gems/ruby/lib/ruby/gems/2.0.0/gems/railties-4.0.4/lib/rails/commands/console.rb:90:in `start'
        from D:/Ruby/ruby gems/ruby/lib/ruby/gems/2.0.0/gems/railties-4.0.4/lib/rails/commands/console.rb:9:in `start'
        from D:/Ruby/ruby gems/ruby/lib/ruby/gems/2.0.0/gems/railties-4.0.4/lib/rails/commands.rb:62:in `<top (required)>'
        from bin/rails:4:in `require'

**Comment by pratibha31** [comment] 2019-02-12 17:45
Any help on this issue. How to resolve this??

**Comment by blowmage** [comment] 2019-02-12 20:16
Can you post the code for what you are doing? How are you setting the proxy?

**Comment by pratibha31** [comment] 2019-02-13 06:30
I am configuring proxy in configure_client method of http_client_adapter.rb
Path is  google-api-ruby-client-0.10.0\lib\google\apis\core\http_client_adapter.rb

def configure_client(client, request) 
    client.transparent_gzip_decompression = true
    if true #request.options.proxy
        #proxy = request.options.proxy
        proxy = URI('http://proxy.xyz.com:8080')
        proxy_user = '*******'
        proxy_pass = '*******'
        client.proxy = sprintf('%s:%d', proxy.host, proxy.port)
        if proxy_user && proxy_pass 
            client.set_proxy_auth proxy_user, proxy_pass
        end
    end
end

**Comment by pratibha31** [comment] 2019-02-13 12:29
I am able to configure proxy for client object.
But now I am getting below error:
Error- #<NoMethodError: undefined method ‘status_code’ for true:TrueClass>

In response I am getting True.

**Comment by blowmage** [comment] 2019-02-13 17:52
I don't think monkey-patching the `configure_client` is an advisable strategy for configuring the proxy. I am curious why you chose to do this instead of using the API provided by `Google::Apis::ClientOptions#proxy_url`? You can either pass the proxy value on each API request:

```ruby
require "google/apis/drive_v2"

drive = Google::Apis::DriveV2::DriveService.new
drive.get_file("123", options: { proxy_url: "http://user:passwd@proxy:8088" })
```

Or you can configure a default value to be used on all API requests:

```ruby
require "google/apis/drive_v2"

Google::Apis::ClientOptions.default.proxy_url = "http://user:passwd@proxy:8088"

drive = Google::Apis::DriveV2::DriveService.new
drive.get_file("123")
```

Again, the version of the gem you are using is 2+ years old. I would advise upgrading to the latest release.

**Comment by blowmage** [comment] 2019-05-28 19:20
Closing as we need more information and haven't had a response.

**Closed by blowmage** 2019-05-28 19:20 UTC
Labels: needs more info, type: question
