### ISSUE TITLE
Refreshing session after long inactivity

### ISSUE THREAD

**Issue by PawelDedio** [googleapis/google-api-ruby-client#870] opened 2020-03-26 19:43 UTC
Hi, I have problem with managing user session after long inactivity. In my app I need to do backup user files to Google drive at some periods. I can successfully backup data just after user sign in, but I need to have ability to do backup even when access token is expired.

Sample scenario:

- User logs in
- I save his access and refresh token to the database
- Few hours after I create new access token using refresh token
- I do backup

Unfortunately documentation is not so clear for that case. 

#### Environment details

  - OS: Ubuntu 16.04
  - Ruby version: 2.5.3
  - Gem name and version: `gem 'google-api-client', '~> 0.37.2'`

#### Code example

Controller for user sign in:
```ruby
def user_credentials
    @authorization ||= begin
                         json_path = ENV['GOOGLE_APPLICATION_CREDENTIALS'].to_s
                         client_secrets = Google::APIClient::ClientSecrets.load(filename = json_path)
                         authorization = client_secrets.to_authorization
                         authorization.scope = 'https://www.googleapis.com/auth/drive'
                         authorization.redirect_uri = v1_google_drive_data_google_auth2_callback_url
                         authorization.access_type = 'offline'

                         authorization
                       end
  end

def callback
    user_credentials.code = params[:code] if params[:code]
    token_response = user_credentials.fetch_access_token

    datum = GoogleDriveDatum.instance
    datum.access_token = token_response['access_token']
    datum.refresh_token = token_response['refresh_token']
    datum.access_token_expire_date = DateTime.now + token_response['expires_in'].seconds
    datum.refresh_token_valid = token_response['refresh_token'].present?
    datum.save
  end
```

Backup job:

```ruby
def user_credentials
    @authorization ||= begin
                         json_path = ENV['GOOGLE_APPLICATION_CREDENTIALS'].to_s
                         client_secrets = Google::APIClient::ClientSecrets.load(filename = json_path)
                         authorization = client_secrets.to_authorization
                         authorization.scope = 'https://www.googleapis.com/auth/drive'

                         authorization
                       end
  end

def authorization
    datum = GoogleDriveDatum.instance

    authorization = user_credentials

    authorization.access_token = datum.access_token
    authorization.refresh_token = datum.refresh_token

    if datum.access_token_expire_date.present? && datum.access_token_expire_date <= DateTime.now + 1.minute
      begin
        token_response = authorization.fetch_access_token # I also tried few other methods here but with the same result
        datum.access_token = token_response['access_token']
        datum.refresh_token = token_response['refresh_token']
        datum.access_token_expire_date = DateTime.now + token_response['expires_in'].seconds
        datum.refresh_token_valid = token_response['refresh_token'].present?
        result = datum.save

      rescue Signet::AuthorizationError
        datum.refresh_token_valid = false
        result = datum.save
      end
    end

    authorization
  end

def initialise_client
    drive = Google::Apis::DriveV2::DriveService.new
    drive.authorization = authorization
    drive
  end
```

With this implementation I receive 401 when I try to send file using `DriveService`, however `GoogleDriveDatum` is updated just before that, which means `authorization.fetch_access_token` returns some tokens.

**Comment by fhinkel** [comment] 2020-12-08 14:24
Hi @PawelDedio , thank you for the detailed bug report. Unfortunately, this issue tracker has limited visibility and scope - basically, it's just for reporting issues with the samples contained here and is only watched by the folks who work on these samples.

We are happy to help you move this bug to venues where it'll get the attention of the appropriate product teams.

* [StackOverflow's Google Drive API and Ruby tags](https://stackoverflow.com/questions/tagged/google-drive-api+ruby) is most appropriate for design and general troubleshooting.
* [Google Drive API's public issue tracker](https://b.corp.google.com/issues?q=componentid:191650%2B) is most appropriate for bugs and unexpected behavior.
* [Google Drive API Support](https://developers.google.com/drive/api/v3/support)

I'm going to close this issue because the folks who own this repo have no actionable way to resolve it directly, but please let us know if there's anything we can do to help!

**Closed** 2024-02-13 06:02 UTC
Labels: type: question
