### ISSUE TITLE
HTTPClient::KeepAliveDisconnected: Broken pipe Error when connecting to Google Sheets

### ISSUE THREAD

**Issue by supraja-universum** [googleapis/google-api-ruby-client#629] opened 2017-11-03 16:28 UTC
I'm using google spreadsheets to maintain some of my application's data, which gets updated on a daily basis. Though this worked as a charm earlier, for the past one week, every time I try to run the job, I face this error:
**HTTPClient::KeepAliveDisconnected: Broken pipe**

Below is my stack trace:
```
tack trace (show Rails)
…/vendor/ruby-2.3.4/lib/ruby/2.3.0/openssl/
buffering.rb: 322:in `syswrite'
…/vendor/ruby-2.3.4/lib/ruby/2.3.0/openssl/
buffering.rb: 322:in `do_write'
…/vendor/ruby-2.3.4/lib/ruby/2.3.0/openssl/
buffering.rb: 340:in `write'
…3.0/gems/httpclient-2.8.3/lib/httpclient/
ssl_socket.rb:  80:in `<<'
…uby/2.3.0/gems/httpclient-2.8.3/lib/httpclient/
http.rb: 582:in `dump_file'
…uby/2.3.0/gems/httpclient-2.8.3/lib/httpclient/
http.rb: 508:in `dump'
…uby/2.3.0/gems/httpclient-2.8.3/lib/httpclient/
http.rb: 962:in `dump'
…/2.3.0/gems/httpclient-2.8.3/lib/httpclient/
session.rb: 517:in `block in query'
       /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/
timeout.rb:  91:in `block in timeout'
       /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/
timeout.rb: 101:in `timeout'
…/2.3.0/gems/httpclient-2.8.3/lib/httpclient/
session.rb: 515:in `query'
…/2.3.0/gems/httpclient-2.8.3/lib/httpclient/
session.rb: 177:in `query'
…dle/ruby/2.3.0/gems/httpclient-2.8.3/lib/
httpclient.rb:1242:in `do_get_block'
…dle/ruby/2.3.0/gems/httpclient-2.8.3/lib/
httpclient.rb:1019:in `block in do_request'
…dle/ruby/2.3.0/gems/httpclient-2.8.3/lib/
httpclient.rb:1138:in `rescue in protect_keep_alive_disconnected'
…dle/ruby/2.3.0/gems/httpclient-2.8.3/lib/
httpclient.rb:1132:in `protect_keep_alive_disconnected'
…dle/ruby/2.3.0/gems/httpclient-2.8.3/lib/
httpclient.rb:1014:in `do_request'
…dle/ruby/2.3.0/gems/httpclient-2.8.3/lib/
httpclient.rb: 856:in `request'
…ent-0.10.3/lib/google/apis/core/
http_client_adapter.rb:  17:in `block in call'
…bundle/ruby/2.3.0/gems/hurley-0.2/lib/hurley/
client.rb: 252:in `initialize'
…ent-0.10.3/lib/google/apis/core/
http_client_adapter.rb:  16:in `new'
…ent-0.10.3/lib/google/apis/core/
http_client_adapter.rb:  16:in `call'
…bundle/ruby/2.3.0/gems/hurley-0.2/lib/hurley/
client.rb: 122:in `call_with_redirects'
…bundle/ruby/2.3.0/gems/hurley-0.2/lib/hurley/
client.rb:  89:in `call'
…bundle/ruby/2.3.0/gems/hurley-0.2/lib/hurley/
client.rb:  71:in `post'
…api-client-0.10.3/lib/google/apis/core/
http_command.rb: 272:in `execute_once'
…api-client-0.10.3/lib/google/apis/core/
http_command.rb: 107:in `block (2 levels) in execute'
…undle/ruby/2.3.0/gems/retriable-3.1.1/lib/
retriable.rb:  61:in `block in retriable'
…undle/ruby/2.3.0/gems/retriable-3.1.1/lib/
retriable.rb:  57:in `times'
…undle/ruby/2.3.0/gems/retriable-3.1.1/lib/
retriable.rb:  57:in `retriable'
…api-client-0.10.3/lib/google/apis/core/
http_command.rb: 104:in `block in execute'
…undle/ruby/2.3.0/gems/retriable-3.1.1/lib/
retriable.rb:  61:in `block in retriable'
…undle/ruby/2.3.0/gems/retriable-3.1.1/lib/
retriable.rb:  57:in `times'
…undle/ruby/2.3.0/gems/retriable-3.1.1/lib/
retriable.rb:  57:in `retriable'
…api-client-0.10.3/lib/google/apis/core/
http_command.rb:  96:in `execute'
…api-client-0.10.3/lib/google/apis/core/
base_service.rb: 353:in `execute_or_queue_command'
…api-client-0.10.3/lib/google/apis/core/
base_service.rb: 246:in `http'
…gle_drive-2.1.2/lib/google_drive/
api_client_fetcher.rb:  33:in `request_raw'
….0/gems/google_drive-2.1.2/lib/google_drive/
session.rb: 479:in `block in request'
….0/gems/google_drive-2.1.2/lib/google_drive/
session.rb: 478:in `loop'
….0/gems/google_drive-2.1.2/lib/google_drive/
session.rb: 478:in `request'
…/gems/google_drive-2.1.2/lib/google_drive/
worksheet.rb: 371:in `save'

```

Any idea why this happens?
Thanks in advance

**Comment by bantini** [comment] 2017-11-03 21:54
@supraja-universum What is the version of Ruby, and OS that you are using? Also, can you share the code that is causing the problem?

**Comment by supraja-universum** [comment] 2017-11-04 08:29
I'm using Ruby 2.3.04, in a linux platform. The app is hosted on Heroku.
Also, I am using this feature for 3 different spreadsheet integrations. The other two integrations work good, except for this one.
This error occurs when i call **worksheet.save**

**Comment by ian** [comment] 2017-11-14 02:47
I'm getting this on any request to Gmail send with > 1 attachment.  Server just hangs up on me.

Wondering if something changed recently as some of our API calls are failing now.

**Comment by hypper** [comment] 2018-04-06 13:55
The same trouble while spreadsheet.save
HTTPClient::KeepAliveDisconnected: HTTPClient::KeepAliveDisconnected: Broken pipe
  ./gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:524:in `rescue in query'
  ./gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:514:in `query'
  ./gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
  ./gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
  ./gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
  ./gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1138:in `rescue in protect_keep_alive_disconnected'
  ./gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1132:in `protect_keep_alive_disconnected'
  ./gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
  ./gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:856:in `request'
  ./gems/2.3.0/gems/google-api-client-0.10.3/lib/google/apis/core/http_client_adapter.rb:17:in `block in call'
  ./gems/2.3.0/gems/hurley-0.2/lib/hurley/client.rb:252:in `initialize'
  ./gems/2.3.0/gems/google-api-client-0.10.3/lib/google/apis/core/http_client_adapter.rb:16:in `new'
  ./gems/2.3.0/gems/google-api-client-0.10.3/lib/google/apis/core/http_client_adapter.rb:16:in `call'
  ./gems/2.3.0/gems/hurley-0.2/lib/hurley/client.rb:122:in `call_with_redirects'
  ./gems/2.3.0/gems/hurley-0.2/lib/hurley/client.rb:89:in `call'
  ./gems/2.3.0/gems/hurley-0.2/lib/hurley/client.rb:71:in `post'
  ./gems/2.3.0/gems/google-api-client-0.10.3/lib/google/apis/core/http_command.rb:272:in `execute_once'
  ./gems/2.3.0/gems/google-api-client-0.10.3/lib/google/apis/core/http_command.rb:107:in `block (2 levels) in execute'
  ./gems/2.3.0/gems/retriable-3.1.1/lib/retriable.rb:61:in `block in retriable'
  ./gems/2.3.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `times'
  ./gems/2.3.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `retriable'
  ./gems/2.3.0/gems/google-api-client-0.10.3/lib/google/apis/core/http_command.rb:104:in `block in execute'
  ./gems/2.3.0/gems/retriable-3.1.1/lib/retriable.rb:61:in `block in retriable'
  ./gems/2.3.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `times'
  ./gems/2.3.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `retriable'
  ./gems/2.3.0/gems/google-api-client-0.10.3/lib/google/apis/core/http_command.rb:96:in `execute'
  ./gems/2.3.0/gems/google-api-client-0.10.3/lib/google/apis/core/base_service.rb:353:in `execute_or_queue_command'
  ./gems/2.3.0/gems/google-api-client-0.10.3/lib/google/apis/core/base_service.rb:246:in `http'
  ./gems/2.3.0/gems/google_drive-2.1.2/lib/google_drive/api_client_fetcher.rb:33:in `request_raw'
  ./gems/2.3.0/gems/google_drive-2.1.2/lib/google_drive/session.rb:479:in `block in request'
  ./gems/2.3.0/gems/google_drive-2.1.2/lib/google_drive/session.rb:478:in `loop'
  ./gems/2.3.0/gems/google_drive-2.1.2/lib/google_drive/session.rb:478:in `request'
  ./gems/2.3.0/gems/google_drive-2.1.2/lib/google_drive/worksheet.rb:371:in `save'

Ruby 2.3.1
FreeBSD 11.1-RELEASE

**Comment by hypper** [comment] 2018-04-06 14:09
The same with the newest version

HTTPClient::KeepAliveDisconnected: HTTPClient::KeepAliveDisconnected: Broken pipe
  ./gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:524:in `rescue in query'
  ./gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:514:in `query'
  ./gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
  ./gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
  ./gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
  ./gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1138:in `rescue in protect_keep_alive_disconnected'
  ./gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1132:in `protect_keep_alive_disconnected'
  ./gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
  ./gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:856:in `request'
  ./gems/2.3.0/gems/google-api-client-0.10.3/lib/google/apis/core/http_client_adapter.rb:17:in `block in call'
  ./gems/2.3.0/gems/hurley-0.2/lib/hurley/client.rb:252:in `initialize'
  ./gems/2.3.0/gems/google-api-client-0.10.3/lib/google/apis/core/http_client_adapter.rb:16:in `new'
  ./gems/2.3.0/gems/google-api-client-0.10.3/lib/google/apis/core/http_client_adapter.rb:16:in `call'
  ./gems/2.3.0/gems/hurley-0.2/lib/hurley/client.rb:122:in `call_with_redirects'
  ./gems/2.3.0/gems/hurley-0.2/lib/hurley/client.rb:89:in `call'
  ./gems/2.3.0/gems/hurley-0.2/lib/hurley/client.rb:71:in `post'
  ./gems/2.3.0/gems/google-api-client-0.10.3/lib/google/apis/core/http_command.rb:272:in `execute_once'
  ./gems/2.3.0/gems/google-api-client-0.10.3/lib/google/apis/core/http_command.rb:107:in `block (2 levels) in execute'
  ./gems/2.3.0/gems/retriable-3.1.1/lib/retriable.rb:61:in `block in retriable'
  ./gems/2.3.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `times'
  ./gems/2.3.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `retriable'
  ./gems/2.3.0/gems/google-api-client-0.10.3/lib/google/apis/core/http_command.rb:104:in `block in execute'
  ./gems/2.3.0/gems/retriable-3.1.1/lib/retriable.rb:61:in `block in retriable'
  ./gems/2.3.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `times'
  ./gems/2.3.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `retriable'
  ./gems/2.3.0/gems/google-api-client-0.10.3/lib/google/apis/core/http_command.rb:96:in `execute'
  ./gems/2.3.0/gems/google-api-client-0.10.3/lib/google/apis/core/base_service.rb:353:in `execute_or_queue_command'
  ./gems/2.3.0/gems/google-api-client-0.10.3/lib/google/apis/core/base_service.rb:246:in `http'
  ./gems/2.3.0/gems/google_drive-2.1.2/lib/google_drive/api_client_fetcher.rb:33:in `request_raw'
  ./gems/2.3.0/gems/google_drive-2.1.2/lib/google_drive/session.rb:479:in `block in request'
  ./gems/2.3.0/gems/google_drive-2.1.2/lib/google_drive/session.rb:478:in `loop'
  ./gems/2.3.0/gems/google_drive-2.1.2/lib/google_drive/session.rb:478:in `request'
  ./gems/2.3.0/gems/google_drive-2.1.2/lib/google_drive/worksheet.rb:371:in `save'

**Comment by TheRoyalTnetennba** [comment] 2018-06-06 00:09
Sorry for the slow response. We’re looking at old questions like this one. Are you still having trouble with the disconnects?

**Comment by TheRoyalTnetennba** [comment] 2018-12-07 19:11
Closing since it seems like the issue was caused by a since-fixed bug in HTTPClient

**Closed** 2018-12-07 19:10 UTC
Labels: type: question
