### ISSUE TITLE
Always getting cannot load such file -- google/apis/firebase_v1beta1

### ISSUE THREAD

**Issue by engtom** [googleapis/google-api-ruby-client#838] opened 2019-10-24 09:17 UTC
I'm having troubles trying to use the Ruby Google API. I can't import the firebase api. Always getting: 
cannot load such file -- google/apis/firebase_v1beta1.

#### Environment details

  - OS: MacOS 10.13.6
  - Ruby version: 2.6.3
  - Gem name and version: google-client-api 0,33

#### Code example

require 'google/apis/firebase_v1beta1'

FirebaseService = Google::Apis::FirebaseV1beta1

**Comment by dazuma** [comment] 2019-10-24 22:07
I'm not able to reproduce this (on Ruby 2.6.5, google-api-client 0.33.1, MacOS 10.14.6).

Are you using bundler? If so, is google-api-client in your Gemfile? If not, how are you determining that the gem is installed and loaded?

**Comment by engtom** [comment] 2019-10-28 22:47
Yes, it is. Importing drive_v2, for example, works well. No errors. Only importing firebase the errors show up.

**Comment by dazuma** [comment] 2019-10-28 23:40
Well, this one is a puzzler. I still can't reproduce, even when I match your Ruby and google-api-client versions exactly. (My test Mac is on Mojave, so I can't match your OS, but I can't imagine that would matter.) In the past when we've observed something like this, it's been due to incorrect permissions on the file, but the file looks correct in this case.

What I'd suggest:
* Delete and retype your `require` line. Just in case you accidentally typed a weird character originally.
* Uninstall and reinstall the gem. Just to rule out something weird having happened to the file in your local filesystem.

**Comment by fhinkel** [comment] 2020-12-08 09:32
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.

**Closed by fhinkel** 2020-12-08 09:32 UTC
Labels: type: question
