### ISSUE TITLE
Timeout using the gem but same request with curl pass

### ISSUE THREAD

**Issue by zevarito** [googleapis/google-api-ruby-client#773] opened 2019-03-12 18:10 UTC
#### Environment details

  - OS: `OSX High Sierra`
  - Ruby version: `2.3.1`
  - Gem name and version:  `google-api-client 0.28.4`

#### Steps to reproduce

  Trying to list channel sections returns
```
Caught error execution expired
Error - #<HTTPClient::ConnectTimeoutError: execution expired>
Completed 500 Internal Server Error in 60009ms (ActiveRecord: 3.0ms)
Google::Apis::TransmissionError (execution expired)
```
#### Code example

```ruby
service.list_channel_sections('snippet,contentDetails', channel_id: 'XXXXXX')
```
The following is the URL logged in the console, which if used straight with curl works just fine.

`https://www.googleapis.com/youtube/v3/channelSections?channelId=XXXXX&key=XXXX&part=snippet%2CcontentDetails`

**Comment by xofred** [comment] 2019-05-15 04:11
Me too! I am using shadowsocks as HTTP proxy in OS X command line
```shell
curl https://www.googleapis.com/androidpublisher/v3/applications/com.live18.app/inappproducts\?
```
```json
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "required",
    "message": "Login Required",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Login Required"
 }
}
```
```shell
rails c
```
> Loading development environment (Rails 5.2.3)
> [1] pry(main)> rp = AndroidPublisher::list_inappproducts
> Sending HTTP get https://www.googleapis.com/androidpublisher/v3/applications/com.live18.app/inappproducts?
> Caught error execution expired
> Error - #<Faraday::ConnectionFailed wrapped=#<Net::OpenTimeout: execution expired>>
>
> Faraday::ConnectionFailed: execution expired
> from /Users/justin/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/net/http.rb:947:in `initialize'
> Caused by Net::OpenTimeout: execution expired
> from /Users/justin/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/net/http.rb:947:in `initialize'

**Comment by xofred** [comment] 2019-05-15 07:10
I give up using shadowsocks as http proxy, such as export http_proxy="host:port" to env, and start using [outline](https://s3.amazonaws.com/outline-vpn/index.html#/zh-CN/home). And it worked!
![image](https://user-images.githubusercontent.com/2174219/57755447-89bdf880-7723-11e9-8e3e-6fa19e847e4c.png)

**Comment by dazuma** [comment] 2019-07-23 19:36
@zevarito Is this still happening for you? And are you going through an http proxy (as xofred was)?

**Comment by zevarito** [comment] 2019-07-25 21:08
@dazuma I didn't notice lately.

**Comment by dazuma** [comment] 2019-11-11 22:14
I'm not able to reproduce this either. It's likely that the timeout setting was incorrect for a period of time but was subsequently corrected. I'm going to close this, but feel free to reopen if this reoccurs.

**Closed by dazuma** 2019-11-11 22:14 UTC
Labels: status: investigating, type: question
