### ISSUE TITLE
Please consider breaking this up into individual API gems

### ISSUE THREAD

**Issue by tas50** [googleapis/google-api-ruby-client#1314] opened 2020-10-28 16:58 UTC
**Is your feature request related to a problem? Please describe.**

This gem is getting rather large and includes files for many APIs that the user may not require.

 **Describe the solution you'd like**

It would be very helpful to provide a more granular set of API gems like Amazon does with the aws-sdk gems.

 **Describe alternatives you've considered**
???

 **Additional context**
We ship this gem in customer software and the size greatly impacts the overall size of our product. We utilize a small number of actual APIs. We could reduce the total footprint of this package by 90% if we could selectively choose which gems to use.

**Comment by dazuma** [comment] 2020-10-28 18:40
Yes, this is being actively worked on as we speak. My guess is that it will be sometime in December before we actually have the library broken up (as we have to update the generation process, the release process, a bunch of details.) Please follow #450 for updates. I'm going to close this as a duplicate of #450.

**Closed by dazuma** 2020-10-28 18:40 UTC
Labels: type: feature request

**Comment by tas50** [comment] 2020-10-28 18:59
Perfect. Thanks @dazuma
