### ISSUE TITLE
Uninitialized constant Google::Apis::DriveV3::File::Representation

### ISSUE THREAD

**Issue by ta6o** [googleapis/google-api-ruby-client#832] opened 2019-10-05 07:30 UTC
Hi,

I've been running into this problem while trying to get a spreadsheet with [google-drive gem](https://github.com/gimite/google-drive-ruby) by any means (key, url, title, name) since I tried to use **Patron** as adapter for **Faraday**:

`NameError (uninitialized constant Google::Apis::DriveV3::File::Representation)`

Relevant part of the code:

```
session = GoogleDrive.saved_session("token.json", nil, api_id, api_key)
file = session.spreadsheet_by_key("<SPREADHEET_KEY>")
```

The authorization succeeds (session object is created successfully), but I get this error while trying to access the sheet:

```
        5: from (irb):1
        4: from /home/project/lib/elastic.rb:34:in `check_content'
        3: from /home/.rvm/gems/ruby-2.6.0@u95-panel/gems/google_drive-3.0.3/lib/google_drive/session.rb:335:in `spreadsheet_by_key'
        2: from /home/.rvm/gems/ruby-2.6.0@u95-panel/gems/google_drive-3.0.3/lib/google_drive/session.rb:290:in `file_by_id'
        1: from /home/.rvm/gems/ruby-2.6.0@u95-panel/gems/google-api-client-0.32.0/generated/google/apis/drive_v3/service.rb:1097:in `get_file'
NameError (uninitialized constant Google::Apis::DriveV3::File::Representation)
```

I tried requiring the source files manually in the console, although the **Representation** class is defined there, it is not accessible.

I have completely erased all installed gems and bundled again, used different versions of **google-api-client** (0.30.10 and 0.32.0) but no luck. 

Tried with ruby versions 2.6.0 and 2.6.3.

Tried on 2 different machines, one running Arch Linux (5.3.1-arch1-1-ARCH), the other Ubuntu (4.15.0-64-generic).

I'd appreciate any hint to overcome the issue.

Thanks in advance.

**Comment by dazuma** [comment] 2020-04-14 01:47
@ta6o Are you sure the stack trace you have above is accurate? It implies you have google_drive 3.0.3 and google-api-client 0.32.0 installed, but it seems impossible that your bundle could have that, since google_drive 3.0.3 requires google-api-client <0.31.0. (See https://rubygems.org/gems/google_drive/versions/3.0.3)

**Comment by dazuma** [comment] 2020-04-14 01:51
Also, if you can reproduce this by requiring source files manually in the console, can you paste in your console session? I'm not able to reproduce that.

```
▶ bundle exec irb
irb(main):001:0> require "google/apis/version"
=> true
irb(main):002:0> Google::Apis::VERSION
=> "0.32.0"
irb(main):003:0> require "google/apis/drive_v3"
=> true
irb(main):004:0> Google::Apis::DriveV3::File::Representation
=> Google::Apis::DriveV3::File::Representation
irb(main):005:0>
```

**Comment by fhinkel** [comment] 2020-12-08 09:32
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.

**Closed by fhinkel** 2020-12-08 09:32 UTC
Labels: api: drive, type: question
